### ISSUE TITLE
Bug sobre documentacion

### ISSUE THREAD

**Issue by icebeam7** [icebeam7/UTBBackendApi#6]
Este bug esta relacionado con  #5

**Comment by icebeam7** [comment]
Tambien tiene que ver con #2

**Comment by icebeam7** [comment]
![jacket](https://github.com/user-attachments/assets/0bac10f2-a81b-4dd3-83d9-5352075e4428)

**Comment by guztorti** [comment]
A donde se compra esa chaqueta ⬆️

**Comment by icebeam7** [comment]
Saludos, se compra en Amazon
